
-- when adding new new enums you likely will need to update the global_game.d.luau in order to add type checking to them.

return {
    KeyCodes = {
        a = "a",
        b = "b",
        c = "c",
        d = "d",
        e = "e",
        f = "f",
        g = "g",
        h = "h",
        i = "i",
        j = "j",
        k = "k",
        l = "l",
        m = "m",
        n = "n",
        o = "o",
        p = "p",
        q = "q",
        r = "r",
        s = "s",
        t = "t",
        u = "u",
        v = "v",
        w = "w",
        x = "x",
        y = "y",
        z = "z",

        ["0"] = "0",
        ["1"] = "1",
        ["2"] = "2",
        ["3"] = "3",
        ["4"] = "4",
        ["5"] = "5",
        ["6"] = "6",
        ["7"] = "7",
        ["8"] = "8",
        ["9"] = "9",

        ["space"] = "space",
        ["return"] = "return",
        ["backspace"] = "backspace",
        ["tab"] = "tab",
        ["escape"] = "escape",
        ["delete"] = "delete",
        ["lshift"] = "lshift",
        ["rshift"] = "rshift",
        ["lctrl"] = "lctrl",
        ["rctrl"] = "rctrl",
        ["lalt"] = "lalt",
        ["ralt"] = "ralt",
        ["lgui"] = "lgui",
        ["rgui"] = "rgui",
        ["apps"] = "apps",
        ["pause"] = "pause",
        ["capslock"] = "capslock",
        ["scrolllock"] = "scrolllock",
        ["numlock"] = "numlock",
        ["printscreen"] = "printscreen",
        ["insert"] = "insert",
        ["home"] = "home",
        ["end"] = "end",
        ["pageup"] = "pageup",
        ["pagedown"] = "pagedown",

        ["up"] = "up",
        ["down"] = "down",
        ["left"] = "left",
        ["right"] = "right",

        Minus       = "-",
        Equals      = "=",
        LeftBracket = "[",
        RightBracket= "]",
        Backslash   = "\\",
        Semicolon   = ";",
        Apostrophe  = "'",
        Comma       = ",",
        Period      = ".",
        Slash       = "/",
        Backtick    = "`",
        
        f1 = "f1",
        f2 = "f2",
        f3 = "f3",
        f4 = "f4",
        f5 = "f5",
        f6 = "f6",
        f7 = "f7",
        f8 = "f8",
        f9 = "f9",
        f10 = "f10",
        f11 = "f11",
        f12 = "f12",
        f13 = "f13",
        f14 = "f14",
        f15 = "f15",

        Numpad1 = "kp1";
        Numpad2 = "kp2";
        Numpad3 = "kp3";
        Numpad4 = "kp4";
        Numpad5 = "kp4";
        Numpad6 = "kp5";
        Numpad7 = "kp6";
        Numpad8 = "kp7";
        Numpad9 = "kp8";
        Numpad0 = "kp9";

        mouse_left="leftclick",
        mouse_right="rightclick",
        mouse_middle="middleclick",
        wheel_up="wheel_up",
        wheel_down ="wheel_down"
    },

    CursorTypes = {
        Arrow      = "arrow",
        IBeam      = "ibeam",
        Wait       = "wait",
        Crosshair  = "crosshair",
        SizeNWSE   = "sizenwse",
        SizeNESW   = "sizenesw",
        SizeWE     = "sizewe",
        SizeNS     = "sizens",
        SizeAll    = "sizeall",
        Hand       = "hand"
    }
}